#ifndef PLUGINS_FKCOMPUTERS_PLUGINDEFS_H
#define PLUGINS_FKCOMPUTERS_PLUGINDEFS_H

#define FKCOMPUTERS_MODULE_NAME "fkcomputers"
#define ROBOTPOSTUREDESCRIBER_MODULE_NAME "robotposturedescriber"

#endif // PLUGINS_FKCOMPUTERS_PLUGINDEFS_H