/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 31 generated on 2011-02-15 23:18:20.055189
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object:
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -shared -Wl,-soname,ik.so -o ik.so ik.cpp
#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#ifdef BOOST_ASSERT
#define IKFAST_ASSERT BOOST_ASSERT
#else

#include <stdexcept>
#include <sstream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  6.28318530717959
#define IKPI  3.14159265358979
#define IKPI_2  1.57079632679490

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#endif // _MSC_VER

// defined when creating a shared object/dll
#ifdef IKFAST_CLIBRARY
#ifdef _MSC_VER
#define IKFAST_API extern "C" __declspec(dllexport)
#else
#define IKFAST_API extern "C"
#endif
#else
#define IKFAST_API
#endif

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

typedef double IKReal;
class IKSolution
{
public:
    /// Gets a solution given its free parameters
    /// \param pfree The free parameters required, range is in [-pi,pi]
    void GetSolution(IKReal* psolution, const IKReal* pfree) const {
        for(size_t i = 0; i < basesol.size(); ++i) {
            if( basesol[i].freeind < 0 )
                psolution[i] = basesol[i].foffset;
            else {
                IKFAST_ASSERT(pfree != NULL);
                psolution[i] = pfree[basesol[i].freeind]*basesol[i].fmul + basesol[i].foffset;
                if( psolution[i] > IKPI ) {
                    psolution[i] -= IK2PI;
                }
                else if( psolution[i] < -IKPI ) {
                    psolution[i] += IK2PI;
                }
            }
        }
    }

    /// Gets the free parameters the solution requires to be set before a full solution can be returned
    /// \return vector of indices indicating the free parameters
    const std::vector<int>& GetFree() const { return vfree; }

    struct VARIABLE
    {
        VARIABLE() : freeind(-1), fmul(0), foffset(0) {}
        VARIABLE(int freeind, IKReal fmul, IKReal foffset) : freeind(freeind), fmul(fmul), foffset(foffset) {}
        int freeind;
        IKReal fmul, foffset; ///< joint value is fmul*sol[freeind]+foffset
    };

    std::vector<VARIABLE> basesol;       ///< solution and their offsets if joints are mimiced
    std::vector<int> vfree;
};

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1.001f && f < 1.001f ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1.001 && f < 1.001 ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline float IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1.001f && f < 1.001f ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0.0f;
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1.001 && f < 1.001 ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0.0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) )
        return 0;
    return atan2f(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) )
        return 0;
    return atan2(fy,fx);
}

IKFAST_API int getNumFreeParameters() { return 0; }
IKFAST_API int* getFreeParameters() { return NULL; }
IKFAST_API int getNumJoints() { return 2; }

IKFAST_API int getIKRealSize() { return sizeof(IKReal); }

IKFAST_API int getIKType() { return 0x23000006; }

/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void fk(const IKReal* j, IKReal* eetrans, IKReal* eerot) {
IKReal x0,x1,x2,x3;
x0=IKcos(j[0]);
x1=IKsin(j[0]);
x2=IKsin(j[1]);
x3=IKcos(j[1]);
eetrans[0]=((-0.0170700000000000)+(((0.0680000000000000)*(x0)))+(((-0.0300000000000000)*(x1)))+(((0.0232000000000000)*(x0)*(x3)))+(((0.0980000000000000)*(x0)*(x2))));
eetrans[1]=((((0.0680000000000000)*(x1)))+(((0.0232000000000000)*(x1)*(x3)))+(((0.0300000000000000)*(x0)))+(((0.0980000000000000)*(x1)*(x2))));
eetrans[2]=((0.381450000000000)+(((-0.0232000000000000)*(x2)))+(((0.0980000000000000)*(x3))));
eerot[0]=((x0)*(x3));
eerot[1]=((x1)*(x3));
eerot[2]=((-1.00000000000000)*(x2));
}

class IKSolver {
public:
IKReal j13, cj13, sj13,
j14, cj14, sj14,
new_r00, r00, rxp0_0,
new_r01, r01, rxp0_1,
new_r02, r02, rxp0_2,
new_r10, r10, rxp1_0,
new_r11, r11, rxp1_1,
new_r12, r12, rxp1_2,
new_r20, r20, rxp2_0,
new_r21, r21, rxp2_1,
new_r22, r22, rxp2_2,
new_px, new_py, new_pz, px, py, pz, npx, npy, npz, pp;

bool ik(const IKReal* eetrans, const IKReal* eerot, const IKReal* pfree, std::vector<IKSolution>& vsolutions) {
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
vsolutions.resize(0); vsolutions.reserve(8);
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

new_px=((0.0170700000000000)+(px));
new_py=py;
new_pz=((-0.381450000000000)+(pz));
px = new_px; py = new_py; pz = new_pz;
pp=(((px)*(px))+((py)*(py))+((pz)*(pz)));
{
IKReal dummyeval[1];
IKReal x0=(px)*(px);
dummyeval[0]=((x0)+(((20.4081632653061)*(pz)*(x0)))+(((104.123281965848)*(x0)*((pz)*(pz)))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
{
IKReal evalcond[1];
evalcond[0]=IKabs(px);
if( IKabs(evalcond[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-104.123281965848)*(py)*((pz)*(pz))))+(((-20.4081632653061)*(py)*(pz)))+(((-1.00000000000000)*(py))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
{
IKReal evalcond[1];
evalcond[0]=IKabs(py);
if( IKabs(evalcond[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[8];
IKReal x1=(pz)*(pz);
IKReal x2=((216.262975778547)*(x1));
IKReal x3=((1.00000000000000)+(x2));
dummyeval[0]=x3;
dummyeval[1]=x3;
dummyeval[2]=x3;
dummyeval[3]=x3;
dummyeval[4]=x3;
dummyeval[5]=x3;
dummyeval[6]=x3;
dummyeval[7]=x3;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  || IKabs(dummyeval[2]) < 0.0000100000000000  || IKabs(dummyeval[3]) < 0.0000100000000000  || IKabs(dummyeval[4]) < 0.0000100000000000  || IKabs(dummyeval[5]) < 0.0000100000000000  || IKabs(dummyeval[6]) < 0.0000100000000000  || IKabs(dummyeval[7]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j14array[2], cj14array[2], sj14array[2];
bool j14valid[2]={false};
IKReal x4=(pz)*(pz);
IKReal x5=((0.00462400000000000)+(x4));
IKReal x6=((IKabs(x5) != 0)?((IKReal)1/(x5)):(IKReal)1.0e30);
IKReal x7=((IKabs(x5) != 0)?(pow(x5,-2.00000000000000)):(IKReal)1.0e30);
IKReal x8=((0.0384160000000000)*(x4)*(x7));
IKReal x9=((0.0163200000000000)*(x6));
IKReal x10=((x8)+(((-1.00000000000000)*(x9))));
if( (x10) < (IKReal)-0.00001 )
    continue;
IKReal x11=IKsqrt(x10);
IKReal x12=((24500.0000000000)*(x4));
IKReal x13=((125000.000000000)*(pz)*(x11)*(x5));
IKReal x14=((0.0980000000000000)*(pz)*(x6));
j14array[0]=IKatan2(((-1.44117647058824)+(((5.88235294117647e-5)*(x6)*(((x13)+(x12)))))), ((((0.500000000000000)*(x11)))+(x14)));
sj14array[0]=IKsin(j14array[0]);
cj14array[0]=IKcos(j14array[0]);
j14array[1]=IKatan2(((-1.44117647058824)+(((5.88235294117647e-5)*(x6)*(((((-1.00000000000000)*(x13)))+(x12)))))), ((((-0.500000000000000)*(x11)))+(x14)));
sj14array[1]=IKsin(j14array[1]);
cj14array[1]=IKcos(j14array[1]);
if( j14array[0] > IKPI )
{
    j14array[0]-=IK2PI;
}
else if( j14array[0] < -IKPI )
{    j14array[0]+=IK2PI;
}
j14valid[0] = true;
if( j14array[1] > IKPI )
{
    j14array[1]-=IK2PI;
}
else if( j14array[1] < -IKPI )
{    j14array[1]+=IK2PI;
}
j14valid[1] = true;
if( j14valid[0] && j14valid[1] && IKabs(cj14array[0]-cj14array[1]) < 0.0001 && IKabs(sj14array[0]-sj14array[1]) < 0.0001 )
{
    j14valid[1]=false;
}
for(int ij14 = 0; ij14 < 2; ++ij14)
{
if( !j14valid[ij14] )
{
    continue;
}
j14 = j14array[ij14]; cj14 = cj14array[ij14]; sj14 = sj14array[ij14];

{
IKReal j13array[2], cj13array[2], sj13array[2];
bool j13valid[2]={false};
IKReal x15=((-0.0300000000000000)*(sj14));
IKReal x16=((cj14)*(pz));
IKReal x17=((-0.0980000000000000)+(x16));
IKReal x18=((0.0680000000000000)*(sj14));
IKReal x19=((((-1.00000000000000)*(x18)))+(x17));
IKReal x20=IKatan2(x15, x19);
j13array[0]=((-1.00000000000000)*(x20));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
j13array[1]=((3.14159265358979)+(((-1.00000000000000)*(x20))));
sj13array[1]=IKsin(j13array[1]);
cj13array[1]=IKcos(j13array[1]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
if( j13array[1] > IKPI )
{
    j13array[1]-=IK2PI;
}
else if( j13array[1] < -IKPI )
{    j13array[1]+=IK2PI;
}
j13valid[1] = true;
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
for(int ij13 = 0; ij13 < 2; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}
}
}

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
IKReal op[6+1], zeror[6];
int numroots;
IKReal j14evalpoly[3];
IKReal x21=((20.4081632653061)*(py)*(pz));
IKReal x22=(pz)*(pz);
IKReal x23=((3.30070803831737)*(py));
IKReal x24=(py)*(py)*(py);
IKReal x25=((416.493127863390)*(x24));
IKReal x26=((312.369845897543)*(py)*(x22));
IKReal x27=((2.77551020408163)*(py));
IKReal x28=((28.3215326947105)*(py)*(pz));
IKReal x29=((104.123281965848)*(py)*(x22));
op[0]=((((-1.00000000000000)*(x21)))+(((-1.00000000000000)*(x29)))+(((-1.00000000000000)*(py))));
op[1]=((((-1.00000000000000)*(x27)))+(((-1.00000000000000)*(x28))));
op[2]=((((-1.00000000000000)*(x23)))+(x25)+(x26)+(x21));
op[3]=((56.6430653894211)*(py)*(pz));
op[4]=((((-1.00000000000000)*(x26)))+(((-1.00000000000000)*(x25)))+(x21)+(x23));
op[5]=((((-1.00000000000000)*(x28)))+(x27));
op[6]=((((-1.00000000000000)*(x21)))+(py)+(x29));
polyroots6(op,zeror,numroots);
IKReal j14array[6], cj14array[6], sj14array[6], tempj14array[1];
int numsolutions = 0;
for(int ij14 = 0; ij14 < numroots; ++ij14)
{
IKReal htj14 = zeror[ij14];
tempj14array[0]=((2.00000000000000)*(atan(htj14)));
for(int kj14 = 0; kj14 < 1; ++kj14)
{
j14array[numsolutions] = tempj14array[kj14];
if( j14array[numsolutions] > IKPI )
{
    j14array[numsolutions]-=IK2PI;
}
else if( j14array[numsolutions] < -IKPI )
{
    j14array[numsolutions]+=IK2PI;
}
sj14array[numsolutions] = IKsin(j14array[numsolutions]);
cj14array[numsolutions] = IKcos(j14array[numsolutions]);
bool valid = true;
for( int kj14 = 0; kj14 < numsolutions; ++kj14)
{
    if( IKabs(cj14array[kj14]-cj14array[numsolutions]) < 0.0001 && IKabs(sj14array[kj14]-sj14array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij14 = 0; ij14 < numsolutions; ++ij14)
    {
    j14 = j14array[ij14]; cj14 = cj14array[ij14]; sj14 = sj14array[ij14];

j14evalpoly[0]=((py)*(sj14));
j14evalpoly[1]=((((-1.00000000000000)*(py)))+(((py)*((cj14)*(cj14)))));
j14evalpoly[2]=((cj14)*(py));
if( IKabs(j14evalpoly[0]) < 0.0000001000000000  || IKabs(j14evalpoly[1]) < 0.0000001000000000  || IKabs(j14evalpoly[2]) < 0.0000001000000000  )
{
    continue;
}
IKReal x30=((IKabs(py) != 0)?(pow(py,-2.00000000000000)):(IKReal)1.0e30);
IKReal x31=((IKabs(sj14) != 0)?(pow(sj14,-2.00000000000000)):(IKReal)1.0e30);
IKReal x32=((IKabs(sj14) != 0)?((IKReal)1/(sj14)):(IKReal)1.0e30);
j14evalpoly[0]=((-181.028240405503)+(((1.73859522085445)*(x30)*(x31)))+(((2.41274438812455)*(x30)*(x32)))+(((181.028240405503)*(x30)*(x31)*((cj14)*(cj14))*((pz)*(pz))))+(((-35.4815351194786)*(cj14)*(pz)*(x30)*(x31)))+(x30)+(((-24.6198406951484)*(cj14)*(pz)*(x30)*(x32))));
if( IKabs(j14evalpoly[0]) > 0.0000001000000000  )
{
    continue;
}
{
IKReal dummyeval[2];
dummyeval[0]=py;
dummyeval[1]=sj14;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
dummyeval[0]=py;
dummyeval[1]=sj14;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
dummyeval[0]=py;
dummyeval[1]=sj14;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal evalcond[3];
evalcond[0]=((IKfmod(((j14)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=0;
evalcond[2]=((0.0980000000000000)+(((-1.00000000000000)*(pz))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=py;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=py;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[5];
evalcond[0]=IKabs(py);
evalcond[1]=-0.0300000000000000;
evalcond[2]=0;
evalcond[3]=((0.0980000000000000)+(((-1.00000000000000)*(pz))));
evalcond[4]=((0.0105040000000000)+(((-1.00000000000000)*((pz)*(pz)))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
continue;

} else
{
IKReal op[2+1], zeror[2];
int numroots;
IKReal x33=((10.2040816326531)*(pz));
op[0]=((-1.00000000000000)+(x33));
op[1]=0;
op[2]=((1.00000000000000)+(((-1.00000000000000)*(x33))));
polyroots2(op,zeror,numroots);
IKReal j13array[2], cj13array[2], sj13array[2], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
IKReal op[1+1], zeror[1];
int numroots;
op[0]=((-1.00000000000000)+(((10.2040816326531)*(pz))));
op[1]=0;
polyroots1(op,zeror,numroots);
IKReal j13array[1], cj13array[1], sj13array[1], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
{
IKReal j13array[4], cj13array[4], sj13array[4];
bool j13valid[4]={false};
IKReal x34=x30;
IKReal x35=((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30);
IKReal x36=x22;
IKReal x37=((0.0105040000000000)+(((-1.00000000000000)*(x36))));
if( (x37) < (IKReal)-0.00001 )
    continue;
IKReal x38=IKsqrt(x37);
cj13array[0]=((-1.00000000000000)*(x35)*(x38));
cj13array[2]=((x35)*(x38));
if( cj13array[0] >= -1.0001 && cj13array[0] <= 1.0001 )
{
    j13valid[0] = j13valid[1] = true;
    j13array[0] = IKacos(cj13array[0]);
    sj13array[0] = IKsin(j13array[0]);
    cj13array[1] = cj13array[0];
    j13array[1] = -j13array[0];
    sj13array[1] = -sj13array[0];
}
else if( isnan(cj13array[0]) )
{
    // probably any value will work
    j13valid[0] = true;
    cj13array[0] = 1; sj13array[0] = 0; j13array[0] = 0;
}
if( cj13array[2] >= -1.0001 && cj13array[2] <= 1.0001 )
{
    j13valid[2] = j13valid[3] = true;
    j13array[2] = IKacos(cj13array[2]);
    sj13array[2] = IKsin(j13array[2]);
    cj13array[3] = cj13array[2];
    j13array[3] = -j13array[2];
    sj13array[3] = -sj13array[2];
}
else if( isnan(cj13array[2]) )
{
    // probably any value will work
    j13valid[2] = true;
    cj13array[2] = 1; sj13array[2] = 0; j13array[2] = 0;
}
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
if( j13valid[0] && j13valid[2] && IKabs(cj13array[0]-cj13array[2]) < 0.0001 && IKabs(sj13array[0]-sj13array[2]) < 0.0001 )
{
    j13valid[2]=false;
}
if( j13valid[0] && j13valid[3] && IKabs(cj13array[0]-cj13array[3]) < 0.0001 && IKabs(sj13array[0]-sj13array[3]) < 0.0001 )
{
    j13valid[3]=false;
}
if( j13valid[1] && j13valid[2] && IKabs(cj13array[1]-cj13array[2]) < 0.0001 && IKabs(sj13array[1]-sj13array[2]) < 0.0001 )
{
    j13valid[2]=false;
}
if( j13valid[1] && j13valid[3] && IKabs(cj13array[1]-cj13array[3]) < 0.0001 && IKabs(sj13array[1]-sj13array[3]) < 0.0001 )
{
    j13valid[3]=false;
}
if( j13valid[2] && j13valid[3] && IKabs(cj13array[2]-cj13array[3]) < 0.0001 && IKabs(sj13array[2]-sj13array[3]) < 0.0001 )
{
    j13valid[3]=false;
}
for(int ij13 = 0; ij13 < 4; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j13array[2], cj13array[2], sj13array[2];
bool j13valid[2]={false};
cj13array[0]=((0.0300000000000000)*(((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30)));
if( cj13array[0] >= -1.0001 && cj13array[0] <= 1.0001 )
{
    j13valid[0] = j13valid[1] = true;
    j13array[0] = IKacos(cj13array[0]);
    sj13array[0] = IKsin(j13array[0]);
    cj13array[1] = cj13array[0];
    j13array[1] = -j13array[0];
    sj13array[1] = -sj13array[0];
}
else if( isnan(cj13array[0]) )
{
    // probably any value will work
    j13valid[0] = true;
    cj13array[0] = 1; sj13array[0] = 0; j13array[0] = 0;
}
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
for(int ij13 = 0; ij13 < 2; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
evalcond[0]=((IKfmod(((-3.14159265358979)+(j14)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=0;
evalcond[2]=((0.0980000000000000)+(pz));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=py;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=py;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[5];
evalcond[0]=IKabs(py);
evalcond[1]=0.0300000000000000;
evalcond[2]=0;
evalcond[3]=((0.0980000000000000)+(pz));
evalcond[4]=((0.0105040000000000)+(((-1.00000000000000)*((pz)*(pz)))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((-10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((-10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
continue;

} else
{
IKReal op[2+1], zeror[2];
int numroots;
IKReal x39=((10.2040816326531)*(pz));
op[0]=((-1.00000000000000)+(((-1.00000000000000)*(x39))));
op[1]=0;
op[2]=((1.00000000000000)+(x39));
polyroots2(op,zeror,numroots);
IKReal j13array[2], cj13array[2], sj13array[2], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
IKReal op[1+1], zeror[1];
int numroots;
op[0]=((-1.00000000000000)+(((-10.2040816326531)*(pz))));
op[1]=0;
polyroots1(op,zeror,numroots);
IKReal j13array[1], cj13array[1], sj13array[1], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
{
IKReal j13array[4], cj13array[4], sj13array[4];
bool j13valid[4]={false};
IKReal x40=x30;
IKReal x41=((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30);
IKReal x42=x22;
IKReal x43=((0.0105040000000000)+(((-1.00000000000000)*(x42))));
if( (x43) < (IKReal)-0.00001 )
    continue;
IKReal x44=IKsqrt(x43);
cj13array[0]=((-1.00000000000000)*(x41)*(x44));
cj13array[2]=((x41)*(x44));
if( cj13array[0] >= -1.0001 && cj13array[0] <= 1.0001 )
{
    j13valid[0] = j13valid[1] = true;
    j13array[0] = IKacos(cj13array[0]);
    sj13array[0] = IKsin(j13array[0]);
    cj13array[1] = cj13array[0];
    j13array[1] = -j13array[0];
    sj13array[1] = -sj13array[0];
}
else if( isnan(cj13array[0]) )
{
    // probably any value will work
    j13valid[0] = true;
    cj13array[0] = 1; sj13array[0] = 0; j13array[0] = 0;
}
if( cj13array[2] >= -1.0001 && cj13array[2] <= 1.0001 )
{
    j13valid[2] = j13valid[3] = true;
    j13array[2] = IKacos(cj13array[2]);
    sj13array[2] = IKsin(j13array[2]);
    cj13array[3] = cj13array[2];
    j13array[3] = -j13array[2];
    sj13array[3] = -sj13array[2];
}
else if( isnan(cj13array[2]) )
{
    // probably any value will work
    j13valid[2] = true;
    cj13array[2] = 1; sj13array[2] = 0; j13array[2] = 0;
}
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
if( j13valid[0] && j13valid[2] && IKabs(cj13array[0]-cj13array[2]) < 0.0001 && IKabs(sj13array[0]-sj13array[2]) < 0.0001 )
{
    j13valid[2]=false;
}
if( j13valid[0] && j13valid[3] && IKabs(cj13array[0]-cj13array[3]) < 0.0001 && IKabs(sj13array[0]-sj13array[3]) < 0.0001 )
{
    j13valid[3]=false;
}
if( j13valid[1] && j13valid[2] && IKabs(cj13array[1]-cj13array[2]) < 0.0001 && IKabs(sj13array[1]-sj13array[2]) < 0.0001 )
{
    j13valid[2]=false;
}
if( j13valid[1] && j13valid[3] && IKabs(cj13array[1]-cj13array[3]) < 0.0001 && IKabs(sj13array[1]-sj13array[3]) < 0.0001 )
{
    j13valid[3]=false;
}
if( j13valid[2] && j13valid[3] && IKabs(cj13array[2]-cj13array[3]) < 0.0001 && IKabs(sj13array[2]-sj13array[3]) < 0.0001 )
{
    j13valid[3]=false;
}
for(int ij13 = 0; ij13 < 4; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j13array[2], cj13array[2], sj13array[2];
bool j13valid[2]={false};
cj13array[0]=((0.0300000000000000)*(((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30)));
if( cj13array[0] >= -1.0001 && cj13array[0] <= 1.0001 )
{
    j13valid[0] = j13valid[1] = true;
    j13array[0] = IKacos(cj13array[0]);
    sj13array[0] = IKsin(j13array[0]);
    cj13array[1] = cj13array[0];
    j13array[1] = -j13array[0];
    sj13array[1] = -sj13array[0];
}
else if( isnan(cj13array[0]) )
{
    // probably any value will work
    j13valid[0] = true;
    cj13array[0] = 1; sj13array[0] = 0; j13array[0] = 0;
}
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
for(int ij13 = 0; ij13 < 2; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}
}

} else
{
{
IKReal j13array[1], cj13array[1], sj13array[1];
bool j13valid[1]={false};
IKReal x45=((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30);
j13array[0]=IKatan2(((x45)*(((IKabs(sj14) != 0)?((IKReal)1/(sj14)):(IKReal)1.0e30))*(((0.0980000000000000)+(((-1.00000000000000)*(cj14)*(pz)))+(((0.0680000000000000)*(sj14)))))), ((0.0300000000000000)*(x45)));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
for(int ij13 = 0; ij13 < 1; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j13array[1], cj13array[1], sj13array[1];
bool j13valid[1]={false};
IKReal x46=((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30);
j13array[0]=IKatan2(((x46)*(((IKabs(sj14) != 0)?((IKReal)1/(sj14)):(IKReal)1.0e30))*(((0.0980000000000000)+(((-1.00000000000000)*(cj14)*(pz)))+(((0.0680000000000000)*(sj14)))))), ((0.0300000000000000)*(x46)));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
for(int ij13 = 0; ij13 < 1; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j13array[1], cj13array[1], sj13array[1];
bool j13valid[1]={false};
IKReal x47=((IKabs(py) != 0)?((IKReal)1/(py)):(IKReal)1.0e30);
j13array[0]=IKatan2(((x47)*(((IKabs(sj14) != 0)?((IKReal)1/(sj14)):(IKReal)1.0e30))*(((0.0980000000000000)+(((-1.00000000000000)*(cj14)*(pz)))+(((0.0680000000000000)*(sj14)))))), ((0.0300000000000000)*(x47)));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
for(int ij13 = 0; ij13 < 1; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}
    }

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
IKReal op[4+1], zeror[4];
int numroots;
IKReal j14evalpoly[3];
IKReal x48=(px)*(px);
IKReal x49=(pz)*(pz);
IKReal x50=((2.77551020408163)*(x48));
IKReal x51=((28.3215326947105)*(pz)*(x48));
IKReal x52=((104.123281965848)*(x48)*(x49));
IKReal x53=((20.4081632653061)*(pz)*(x48));
op[0]=((x48)+(x53)+(x52));
op[1]=((x51)+(x50));
op[2]=((((-416.493127863390)*((x48)*(x48))))+(((-208.246563931695)*(x48)*(x49)))+(((-416.493127863390)*(x48)*((py)*(py))))+(((4.30070803831737)*(x48))));
op[3]=((x50)+(((-1.00000000000000)*(x51))));
op[4]=((x48)+(x52)+(((-1.00000000000000)*(x53))));
polyroots4(op,zeror,numroots);
IKReal j14array[4], cj14array[4], sj14array[4], tempj14array[1];
int numsolutions = 0;
for(int ij14 = 0; ij14 < numroots; ++ij14)
{
IKReal htj14 = zeror[ij14];
tempj14array[0]=((2.00000000000000)*(atan(htj14)));
for(int kj14 = 0; kj14 < 1; ++kj14)
{
j14array[numsolutions] = tempj14array[kj14];
if( j14array[numsolutions] > IKPI )
{
    j14array[numsolutions]-=IK2PI;
}
else if( j14array[numsolutions] < -IKPI )
{
    j14array[numsolutions]+=IK2PI;
}
sj14array[numsolutions] = IKsin(j14array[numsolutions]);
cj14array[numsolutions] = IKcos(j14array[numsolutions]);
bool valid = true;
for( int kj14 = 0; kj14 < numsolutions; ++kj14)
{
    if( IKabs(cj14array[kj14]-cj14array[numsolutions]) < 0.0001 && IKabs(sj14array[kj14]-sj14array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij14 = 0; ij14 < numsolutions; ++ij14)
    {
    j14 = j14array[ij14]; cj14 = cj14array[ij14]; sj14 = sj14array[ij14];

j14evalpoly[0]=px;
j14evalpoly[1]=((((-33.3333333333333)*(cj14)*(px)*(pz)))+(((2.26666666666667)*(px)*(sj14)))+(((3.26666666666667)*(px)))+(((-1.00000000000000)*(py)*(sj14))));
j14evalpoly[2]=((((-1.00000000000000)*(sj14)*((py)*(py))))+(((-1.00000000000000)*(sj14)*((px)*(px)))));
if( IKabs(j14evalpoly[0]) < 0.0000001000000000  || IKabs(j14evalpoly[1]) < 0.0000001000000000  || IKabs(j14evalpoly[2]) < 0.0000001000000000  )
{
    continue;
}
IKReal x54=(py)*(py)*(py)*(py);
IKReal x55=(px)*(px)*(px)*(px);
IKReal x56=((10000.0000000000)*(x55));
IKReal x57=x48;
IKReal x58=(py)*(py);
IKReal x59=((20000.0000000000)*(x57)*(x58));
IKReal x60=((10000.0000000000)*(x54));
IKReal x61=((x59)+(x56)+(x60));
IKReal x62=((IKabs(x61) != 0)?((IKReal)1/(x61)):(IKReal)1.0e30);
IKReal x63=((IKabs(px) != 0)?((IKReal)1/(px)):(IKReal)1.0e30);
IKReal x64=((IKabs(sj14) != 0)?((IKReal)1/(sj14)):(IKReal)1.0e30);
IKReal x65=((IKabs(sj14) != 0)?(pow(sj14,-2.00000000000000)):(IKReal)1.0e30);
IKReal x66=((IKabs(px) != 0)?(pow(px,-2.00000000000000)):(IKReal)1.0e30);
IKReal x67=((100.000000000000)*(x58));
IKReal x68=((100.000000000000)*(x57));
IKReal x69=((x67)+(x68));
IKReal x70=((-1.00000000000000)*(x69));
IKReal x71=((IKabs(x70) != 0)?((IKReal)1/(x70)):(IKReal)1.0e30);
IKReal x72=(py)*(py)*(py);
IKReal x73=(cj14)*(cj14);
IKReal x74=x49;
j14evalpoly[0]=((-1111.11111111111)+(((65333.3333333333)*(px)*(py)*(x62)*(x64)))+(((148088.888888889)*(x57)*(x62)*(x64)))+(((106711.111111111)*(x57)*(x62)*(x65)))+(((x60)*(x62)*(x66)))+(((148088.888888889)*(x58)*(x62)*(x64)))+(((-1511111.11111111)*(cj14)*(pz)*(x57)*(x62)*(x64)))+(((-666666.666666667)*(cj14)*(px)*(py)*(pz)*(x62)*(x64)))+(((65333.3333333333)*(py)*(x58)*(x62)*(x63)*(x64)))+(((-666666.666666667)*(cj14)*(py)*(pz)*(x58)*(x62)*(x63)*(x64)))+(((51377.7777777778)*(x57)*(x62)))+(((11111111.1111111)*(x57)*(x62)*(x65)*(x73)*(x74)))+(((106711.111111111)*(x58)*(x62)*(x65)))+(((200.000000000000)*(x58)*(x66)*(x71)))+(((61377.7777777778)*(x58)*(x62)))+(((-6666.66666666667)*(cj14)*(py)*(pz)*(x63)*(x64)*(x71)))+(((-2177777.77777778)*(cj14)*(pz)*(x58)*(x62)*(x65)))+(((-2177777.77777778)*(cj14)*(pz)*(x57)*(x62)*(x65)))+(x66)+(((45333.3333333333)*(px)*(py)*(x62)))+(((653.333333333333)*(py)*(x63)*(x64)*(x71)))+(((453.333333333333)*(py)*(x63)*(x71)))+(((45333.3333333333)*(py)*(x58)*(x62)*(x63)))+(((-1511111.11111111)*(cj14)*(pz)*(x58)*(x62)*(x64)))+(((11111111.1111111)*(x58)*(x62)*(x65)*(x73)*(x74))));
if( IKabs(j14evalpoly[0]) > 0.0000001000000000  )
{
    continue;
}
{
IKReal dummyeval[2];
IKReal x75=((33.3333333333333)*(cj14)*(py)*(pz));
IKReal x76=((px)*(sj14));
IKReal x77=((3.26666666666667)*(py));
IKReal x78=((2.26666666666667)*(py)*(sj14));
IKReal x79=((x77)+(x76)+(x78));
IKReal x80=((((-1.00000000000000)*(x79)))+(x75));
dummyeval[0]=x80;
dummyeval[1]=x80;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x81=((33.3333333333333)*(cj14)*(py)*(pz));
IKReal x82=((px)*(sj14));
IKReal x83=((3.26666666666667)*(py));
IKReal x84=((2.26666666666667)*(py)*(sj14));
IKReal x85=((x82)+(x83)+(x84));
IKReal x86=((x81)+(((-1.00000000000000)*(x85))));
dummyeval[0]=x86;
dummyeval[1]=x86;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x87=((2.26666666666667)*(px)*(sj14));
IKReal x88=((3.26666666666667)*(px));
IKReal x89=((x88)+(x87));
IKReal x90=((py)*(sj14));
IKReal x91=((33.3333333333333)*(cj14)*(px)*(pz));
IKReal x92=((x91)+(x90));
IKReal x93=((x89)+(((-1.00000000000000)*(x92))));
dummyeval[0]=x93;
dummyeval[1]=x93;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal evalcond[3];
evalcond[0]=((IKabs(py))+(IKabs(((IKfmod(((j14)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979)))));
evalcond[1]=0;
evalcond[2]=((0.0980000000000000)+(((-1.00000000000000)*(pz))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=px;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[5];
evalcond[0]=IKabs(px);
evalcond[1]=-0.0300000000000000;
evalcond[2]=0;
evalcond[3]=((0.0980000000000000)+(((-1.00000000000000)*(pz))));
evalcond[4]=((0.0105040000000000)+(((-1.00000000000000)*((pz)*(pz)))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
continue;

} else
{
IKReal op[2+1], zeror[2];
int numroots;
IKReal x94=((10.2040816326531)*(pz));
op[0]=((-1.00000000000000)+(x94));
op[1]=0;
op[2]=((1.00000000000000)+(((-1.00000000000000)*(x94))));
polyroots2(op,zeror,numroots);
IKReal j13array[2], cj13array[2], sj13array[2], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
IKReal op[1+1], zeror[1];
int numroots;
op[0]=((-1.00000000000000)+(((10.2040816326531)*(pz))));
op[1]=0;
polyroots1(op,zeror,numroots);
IKReal j13array[1], cj13array[1], sj13array[1], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
{
IKReal j13array[2], cj13array[2], sj13array[2];
bool j13valid[2]={false};
IKReal x95=x66;
IKReal x96=x63;
IKReal x97=((-0.0300000000000000)*(x96));
IKReal x98=x49;
IKReal x99=((x95)*(x98));
IKReal x100=((1.00000000000000)+(x99));
IKReal x101=((0.0105040000000000)*(x95));
IKReal x102=((((-1.00000000000000)*(x101)))+(x100));
if( (x102) < (IKReal)-0.00001 )
    continue;
IKReal x103=IKsqrt(x102);
j13array[0]=IKatan2(x97, x103);
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
j13array[1]=IKatan2(x97, ((-1.00000000000000)*(x103)));
sj13array[1]=IKsin(j13array[1]);
cj13array[1]=IKcos(j13array[1]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
if( j13array[1] > IKPI )
{
    j13array[1]-=IK2PI;
}
else if( j13array[1] < -IKPI )
{    j13array[1]+=IK2PI;
}
j13valid[1] = true;
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
for(int ij13 = 0; ij13 < 2; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
evalcond[0]=((IKabs(py))+(IKabs(((IKfmod(j14, 6.28318530717959))+(-3.14159265358979)))));
evalcond[1]=0;
evalcond[2]=((0.0980000000000000)+(pz));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=px;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[5];
evalcond[0]=IKabs(px);
evalcond[1]=0.0300000000000000;
evalcond[2]=0;
evalcond[3]=((0.0980000000000000)+(pz));
evalcond[4]=((0.0105040000000000)+(((-1.00000000000000)*((pz)*(pz)))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((-10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((-1.00000000000000)+(((-10.2040816326531)*(pz))));
if( IKabs(dummyeval[0]) < 0.0000001000000000  )
{
continue;

} else
{
IKReal op[2+1], zeror[2];
int numroots;
IKReal x104=((10.2040816326531)*(pz));
op[0]=((-1.00000000000000)+(((-1.00000000000000)*(x104))));
op[1]=0;
op[2]=((1.00000000000000)+(x104));
polyroots2(op,zeror,numroots);
IKReal j13array[2], cj13array[2], sj13array[2], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
IKReal op[1+1], zeror[1];
int numroots;
op[0]=((-1.00000000000000)+(((-10.2040816326531)*(pz))));
op[1]=0;
polyroots1(op,zeror,numroots);
IKReal j13array[1], cj13array[1], sj13array[1], tempj13array[1];
int numsolutions = 0;
for(int ij13 = 0; ij13 < numroots; ++ij13)
{
IKReal htj13 = zeror[ij13];
tempj13array[0]=((2.00000000000000)*(atan(htj13)));
for(int kj13 = 0; kj13 < 1; ++kj13)
{
j13array[numsolutions] = tempj13array[kj13];
if( j13array[numsolutions] > IKPI )
{
    j13array[numsolutions]-=IK2PI;
}
else if( j13array[numsolutions] < -IKPI )
{
    j13array[numsolutions]+=IK2PI;
}
sj13array[numsolutions] = IKsin(j13array[numsolutions]);
cj13array[numsolutions] = IKcos(j13array[numsolutions]);
bool valid = true;
for( int kj13 = 0; kj13 < numsolutions; ++kj13)
{
    if( IKabs(cj13array[kj13]-cj13array[numsolutions]) < 0.0001 && IKabs(sj13array[kj13]-sj13array[numsolutions]) < 0.0001 )
    {
        valid=false; break;
    }
}
if( valid ) { numsolutions++; }
}
}
for(int ij13 = 0; ij13 < numsolutions; ++ij13)
    {
    j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
    }

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
{
IKReal j13array[2], cj13array[2], sj13array[2];
bool j13valid[2]={false};
IKReal x105=x66;
IKReal x106=x63;
IKReal x107=((-0.0300000000000000)*(x106));
IKReal x108=x49;
IKReal x109=((x105)*(x108));
IKReal x110=((1.00000000000000)+(x109));
IKReal x111=((0.0105040000000000)*(x105));
IKReal x112=((((-1.00000000000000)*(x111)))+(x110));
if( (x112) < (IKReal)-0.00001 )
    continue;
IKReal x113=IKsqrt(x112);
j13array[0]=IKatan2(x107, x113);
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
j13array[1]=IKatan2(x107, ((-1.00000000000000)*(x113)));
sj13array[1]=IKsin(j13array[1]);
cj13array[1]=IKcos(j13array[1]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
if( j13array[1] > IKPI )
{
    j13array[1]-=IK2PI;
}
else if( j13array[1] < -IKPI )
{    j13array[1]+=IK2PI;
}
j13valid[1] = true;
if( j13valid[0] && j13valid[1] && IKabs(cj13array[0]-cj13array[1]) < 0.0001 && IKabs(sj13array[0]-sj13array[1]) < 0.0001 )
{
    j13valid[1]=false;
}
for(int ij13 = 0; ij13 < 2; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}
}

} else
{
{
IKReal j13array[1], cj13array[1], sj13array[1];
bool j13valid[1]={false};
j13array[0]=IKatan2(((-1.00000000000000)*(((IKabs(((((-3.00000000000000)*(py)*(sj14)))+(((9.80000000000000)*(px)))+(((-100.000000000000)*(cj14)*(px)*(pz)))+(((6.80000000000000)*(px)*(sj14))))) != 0)?((IKReal)1/(((((-3.00000000000000)*(py)*(sj14)))+(((9.80000000000000)*(px)))+(((-100.000000000000)*(cj14)*(px)*(pz)))+(((6.80000000000000)*(px)*(sj14)))))):(IKReal)1.0e30))*(((0.294000000000000)+(((0.204000000000000)*(sj14)))+(((-3.00000000000000)*(cj14)*(pz)))+(((-100.000000000000)*(px)*(py)*(sj14)))))), ((((IKabs(((((980.000000000000)*(px)))+(((680.000000000000)*(px)*(sj14)))+(((-10000.0000000000)*(cj14)*(px)*(pz)))+(((-300.000000000000)*(py)*(sj14))))) != 0)?((IKReal)1/(((((980.000000000000)*(px)))+(((680.000000000000)*(px)*(sj14)))+(((-10000.0000000000)*(cj14)*(px)*(pz)))+(((-300.000000000000)*(py)*(sj14)))))):(IKReal)1.0e30))*(((((-9.00000000000000)*(sj14)))+(((10000.0000000000)*(sj14)*((px)*(px))))))));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
for(int ij13 = 0; ij13 < 1; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j13array[1], cj13array[1], sj13array[1];
bool j13valid[1]={false};
j13array[0]=IKatan2(((((IKabs(((((-680.000000000000)*(py)*(sj14)))+(((10000.0000000000)*(cj14)*(py)*(pz)))+(((-980.000000000000)*(py)))+(((-300.000000000000)*(px)*(sj14))))) != 0)?((IKReal)1/(((((-680.000000000000)*(py)*(sj14)))+(((10000.0000000000)*(cj14)*(py)*(pz)))+(((-980.000000000000)*(py)))+(((-300.000000000000)*(px)*(sj14)))))):(IKReal)1.0e30))*(((((9.00000000000000)*(sj14)))+(((-10000.0000000000)*(sj14)*((py)*(py))))))), ((-1.00000000000000)*(((IKabs(((((-3.00000000000000)*(px)*(sj14)))+(((-6.80000000000000)*(py)*(sj14)))+(((-9.80000000000000)*(py)))+(((100.000000000000)*(cj14)*(py)*(pz))))) != 0)?((IKReal)1/(((((-3.00000000000000)*(px)*(sj14)))+(((-6.80000000000000)*(py)*(sj14)))+(((-9.80000000000000)*(py)))+(((100.000000000000)*(cj14)*(py)*(pz)))))):(IKReal)1.0e30))*(((0.294000000000000)+(((0.204000000000000)*(sj14)))+(((-3.00000000000000)*(cj14)*(pz)))+(((100.000000000000)*(px)*(py)*(sj14)))))));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
for(int ij13 = 0; ij13 < 1; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j13array[1], cj13array[1], sj13array[1];
bool j13valid[1]={false};
j13array[0]=IKatan2(((((IKabs(((((-680.000000000000)*(py)*(sj14)))+(((10000.0000000000)*(cj14)*(py)*(pz)))+(((-980.000000000000)*(py)))+(((-300.000000000000)*(px)*(sj14))))) != 0)?((IKReal)1/(((((-680.000000000000)*(py)*(sj14)))+(((10000.0000000000)*(cj14)*(py)*(pz)))+(((-980.000000000000)*(py)))+(((-300.000000000000)*(px)*(sj14)))))):(IKReal)1.0e30))*(((((9.00000000000000)*(sj14)))+(((-10000.0000000000)*(sj14)*((py)*(py))))))), ((-1.00000000000000)*(((IKabs(((((-3.00000000000000)*(px)*(sj14)))+(((-6.80000000000000)*(py)*(sj14)))+(((-9.80000000000000)*(py)))+(((100.000000000000)*(cj14)*(py)*(pz))))) != 0)?((IKReal)1/(((((-3.00000000000000)*(px)*(sj14)))+(((-6.80000000000000)*(py)*(sj14)))+(((-9.80000000000000)*(py)))+(((100.000000000000)*(cj14)*(py)*(pz)))))):(IKReal)1.0e30))*(((0.294000000000000)+(((0.204000000000000)*(sj14)))+(((-3.00000000000000)*(cj14)*(pz)))+(((100.000000000000)*(px)*(py)*(sj14)))))));
sj13array[0]=IKsin(j13array[0]);
cj13array[0]=IKcos(j13array[0]);
if( j13array[0] > IKPI )
{
    j13array[0]-=IK2PI;
}
else if( j13array[0] < -IKPI )
{    j13array[0]+=IK2PI;
}
j13valid[0] = true;
for(int ij13 = 0; ij13 < 1; ++ij13)
{
if( !j13valid[ij13] )
{
    continue;
}
j13 = j13array[ij13]; cj13 = cj13array[ij13]; sj13 = sj13array[ij13];

IKReal soleval[1];
soleval[0]=((-0.0232000000000000)+(((-1.00000000000000)*(cj14)*(((0.0680000000000000)+(((-1.00000000000000)*(cj13)*(px)))+(((-1.00000000000000)*(py)*(sj13)))))))+(((-1.00000000000000)*(pz)*(sj14))));
if( soleval[0] > 0.0000000000000000  )
{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(2);
solution.basesol[0].foffset = j13;
solution.basesol[1].foffset = j14;
solution.vfree.resize(0);
}
}
}

}

}
    }

}

}
}
return vsolutions.size()>0;
}

static inline void polyroots1(IKReal rawcoeffs[1+1], IKReal rawroots[1], int& numroots) {
    if( rawcoeffs[0] == 0 ) {
        numroots=0;
    }
    else {
        rawroots[0] = -rawcoeffs[1]/rawcoeffs[0];
        numroots=1;
    }
}
static inline void polyroots2(IKReal rawcoeffs[2+1], IKReal rawroots[2], int& numroots) {
    IKReal det = rawcoeffs[1]*rawcoeffs[1]-4*rawcoeffs[0]*rawcoeffs[2];
    if( det < 0 ) {
        numroots=0;
    }
    else if( det == 0 ) {
        rawroots[0] = -0.5*rawcoeffs[1]/rawcoeffs[0];
        numroots = 1;
    }
    else {
        det = IKsqrt(det);
        rawroots[0] = (-rawcoeffs[1]+det)/(2*rawcoeffs[0]);
        rawroots[1] = (-rawcoeffs[1]-det)/(2*rawcoeffs[0]);//rawcoeffs[2]/(rawcoeffs[0]*rawroots[0]);
        numroots = 2;
    }
}
/// Durand-Kerner polynomial root finding method
static inline void polyroots4(IKReal rawcoeffs[4+1], IKReal rawroots[4], int& numroots)
{
    using std::complex;
    IKFAST_ASSERT(rawcoeffs[0] != 0);
    const IKReal tol = 128.0*std::numeric_limits<IKReal>::epsilon();
    complex<IKReal> coeffs[4];
    const int maxsteps = 50;
    for(int i = 0; i < 4; ++i) {
        coeffs[i] = complex<IKReal>(rawcoeffs[i+1]/rawcoeffs[0]);
    }
    complex<IKReal> roots[4];
    IKReal err[4];
    roots[0] = complex<IKReal>(1,0);
    roots[1] = complex<IKReal>(0.4,0.9); // any complex number not a root of unity is works
    err[0] = 1.0;
    err[1] = 1.0;
    for(int i = 2; i < 4; ++i) {
        roots[i] = roots[i-1]*roots[1];
        err[i] = 1.0;
    }
    for(int step = 0; step < maxsteps; ++step) {
        bool changed = false;
        for(int i = 0; i < 4; ++i) {
            if ( err[i] >= tol ) {
                changed = true;
                // evaluate
                complex<IKReal> x = roots[i] + coeffs[0];
                for(int j = 1; j < 4; ++j) {
                    x = roots[i] * x + coeffs[j];
                }
                for(int j = 0; j < 4; ++j) {
                    if( i != j ) {
                        if( roots[i] != roots[j] ) {
                            x /= (roots[i] - roots[j]);
                        }
                    }
                }
                roots[i] -= x;
                err[i] = abs(x);
            }
        }
        if( !changed ) {
            break;
        }
    }
    numroots = 0;
    for(int i = 0; i < 4; ++i) {
        if( IKabs(imag(roots[i])) < std::numeric_limits<IKReal>::epsilon() ) {
            rawroots[numroots++] = real(roots[i]);
        }
    }
}
/// Durand-Kerner polynomial root finding method
static inline void polyroots6(IKReal rawcoeffs[6+1], IKReal rawroots[6], int& numroots)
{
    using std::complex;
    IKFAST_ASSERT(rawcoeffs[0] != 0);
    const IKReal tol = 128.0*std::numeric_limits<IKReal>::epsilon();
    complex<IKReal> coeffs[6];
    const int maxsteps = 50;
    for(int i = 0; i < 6; ++i) {
        coeffs[i] = complex<IKReal>(rawcoeffs[i+1]/rawcoeffs[0]);
    }
    complex<IKReal> roots[6];
    IKReal err[6];
    roots[0] = complex<IKReal>(1,0);
    roots[1] = complex<IKReal>(0.4,0.9); // any complex number not a root of unity is works
    err[0] = 1.0;
    err[1] = 1.0;
    for(int i = 2; i < 6; ++i) {
        roots[i] = roots[i-1]*roots[1];
        err[i] = 1.0;
    }
    for(int step = 0; step < maxsteps; ++step) {
        bool changed = false;
        for(int i = 0; i < 6; ++i) {
            if ( err[i] >= tol ) {
                changed = true;
                // evaluate
                complex<IKReal> x = roots[i] + coeffs[0];
                for(int j = 1; j < 6; ++j) {
                    x = roots[i] * x + coeffs[j];
                }
                for(int j = 0; j < 6; ++j) {
                    if( i != j ) {
                        if( roots[i] != roots[j] ) {
                            x /= (roots[i] - roots[j]);
                        }
                    }
                }
                roots[i] -= x;
                err[i] = abs(x);
            }
        }
        if( !changed ) {
            break;
        }
    }
    numroots = 0;
    for(int i = 0; i < 6; ++i) {
        if( IKabs(imag(roots[i])) < std::numeric_limits<IKReal>::epsilon() ) {
            rawroots[numroots++] = real(roots[i]);
        }
    }
}
};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ik(const IKReal* eetrans, const IKReal* eerot, const IKReal* pfree, std::vector<IKSolution>& vsolutions) {
IKSolver solver;
return solver.ik(eetrans,eerot,pfree,vsolutions);
}

IKFAST_API const char* getKinematicsHash() { return "80f514166e15c34bd64294fc1fdd5ddd"; }

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv)
{
    if( argc != 12+getNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",getNumFreeParameters());
        return 1;
    }

    std::vector<IKSolution> vsolutions;
    std::vector<IKReal> vfree(getNumFreeParameters());
    IKReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ik(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, vsolutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)vsolutions.size());
    std::vector<IKReal> sol(getNumJoints());
    for(size_t i = 0; i < vsolutions.size(); ++i) {
        printf("sol%d (free=%d): ", (int)i, (int)vsolutions[i].GetFree().size());
        std::vector<IKReal> vsolfree(vsolutions[i].GetFree().size());
        vsolutions[i].GetSolution(&sol[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( size_t j = 0; j < sol.size(); ++j)
            printf("%.15f, ", sol[j]);
        printf("\n");
    }
    return 0;
}

#endif
