#ifndef PLUGINS_POSTUREDESCRIBER_PLUGINDEFS_H
#define PLUGINS_POSTUREDESCRIBER_PLUGINDEFS_H

#define POSTUREDESCRIBER_CLASS_NAME  "posturedescriber" // PostureDescriber
#define POSTUREDESCRIBER_MODULE_NAME "posturedescriber" // PostureDescriberModule

#endif // PLUGINS_POSTUREDESCRIBER_PLUGINDEFS_H